updates-mentioned-in-notes
szcompressor/next.szcompressor.github.io pull request #17
Opened 2023-08-23 17:29 UTC by AnilMandavilli594

Added FZ webpage
added the workflow diagram

2023-08-23 18:59 UTC, robertu94 requested changes
See comments

2023-08-23 18:59 UTC, robertu94 commented on hugo.toml
changing the baseURL like this will break the production site.

2023-08-23 18:59 UTC, robertu94 commented on content/en/.DS_Store
Please don't commit .DS_Store entries, and add them to the gitignore.

2023-08-23 19:38 UTC, AnilMandavilli594 commented on hugo.toml
if i doesnt change the baseurl to "/", the page is not working in my local computer

2023-08-23 19:38 UTC, AnilMandavilli594 commented on hugo.toml
Do you have any suggestion about it.

2023-08-25 13:26 UTC, dingwentao commented on hugo.toml
Can we ensure this PR will be merged before next Monday so that we can view the new updates in our weekly meeting?

2023-08-28 13:20 UTC, merged